### ISSUE TITLE
Korean language support :)

### ISSUE THREAD

**Issue by SoYoungCho** [off99555/machine-learning-curriculum#14]
Hi :) I'm So Young, university student interested in ML studying.
Your project is awesome gathering up all the great infos.
If there is a language support, I think a lot of users will use this useful; so I was wondering if there is a translation of this project.
If there isn't, may I translate this proj in to Korean?
It's my first time translating git documents, but I think it could help some Koreans :)
Thank you!

**Comment by offchan42** [comment]
You can fork this repo and translate if you want. But I don't think translating directly into the `README` file is useful. It would clutter the information.
I suggest creating a new file like `README_korean` or something similar and translate there.

In my opinion, if you want to study ML, it's very important to know English because you are being in the front of the field here. You can't rely on other people to translate for you if you get a bug. Translating for people don't fix the cause of the problem. It's like you are giving them fish instead of teaching them how to fish. So, I don't recommend translating it.

The content of each link itself is in English anyway, so just translating the title of each link is not that helpful.

**Comment by SoYoungCho** [comment]
Right, thanks for a great advice!
